### ISSUE TITLE
Getting Started vs. Getting Started Guide

### ISSUE THREAD

**Issue by stfnsr** [keystonejs/keystonejs-site#15]
I noticed that there are two "Getting started" pages - [Getting Started](http://keystonejs.com/getting-started/) and [Getting Started Guide](http://keystonejs.com/docs/getting-started/), with the latter one containing more detailed manual instructions.
Maybe renaming the second one to "Getting Started (Detailed)" or "Getting Started (Manual Instructions)" could help make the difference clearer? 

Also, the detailed guide refers to the generator-keystone repository for instructions about using the generator - we could instead link to [Getting Started](http://keystonejs.com/getting-started/), which presents the same information in a more beginner friendly format :)

**Comment by snowkeeper** [comment]
fixed by #30
