### ISSUE TITLE
Better explain schema creation for newcomers (no mongo expertise)

### ISSUE THREAD

**Issue by jacargentina** [keystonejs/keystonejs-site#19]
On my first try to create a model, i've noted that i'm missed the "name" mapping, and it seems mongo/keystone relies on a _name_ field, OR a mapping to some field to show it on the Admin UI.

Also, its not very clear to me where that _name_ is related to the object key to uniquely identify the object instance?

May be i can do a PR on this if i can understand this first.

**Comment by snowkeeper** [comment]
fixed by #30
