### ISSUE TITLE
Use Transifex to translate the site

### ISSUE THREAD

**Issue by estilles** [keystonejs/keystonejs-site#20]
[Transifex](https://www.transifex.com) is free for OSS projects. With just a few minor changes, which we probably can do programmatically, we can prepare the KeystoneJS site to use Transifex. 

We could easily use something like [jsxgettext](https://www.npmjs.com/package/jsxgettext) to extract the translatable strings, use the Transifex API to upload them any new strings/download the already translated strings, and a custom function to acts perform the string replacement. 

This new workflow would eliminate the need the keep multiple copies of the site in multiple languages. In addition to the fact that we could use collaboration to translate the site in mores languages. 
If you guys like the idea I will submit a PR with the required changes.

**Comment by morenoh149** [comment]
+1

**Comment by JedWatson** [comment]
This looks like a great idea, @JohnnyEstilles. Feel free to suggest whatever changes you think we need to make this possible.

**Comment by estilles** [comment]
Awesome! I'll start working on it this weekend. :-)
