### ISSUE TITLE
Finish implementing the build process

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystonejs-site#34]
Currently, the build process is a WIP that makes it more work than it could be to update keystonejs.com with changes to this repo.

Specifically; there's no static asset build pipeline; changes to LESS / images / client-side javascript has to be manually moved across from the `public` folder into Keystone's `gh-pages` branch, and the built `.html` files need to be moved manually as well.

The current version number should be retrieved dynamically from npm, but for now could be an environment variable specified during build.

We should also add browserify / webpack into the build process to allow for Babel + npm package usage in the site and move away from the ancient javascript that's currently in use.

This actually might be in the sweet spot for webpack, since it has a jade loader; maybe it can handle the entire build process for us - replacing the current `express` and `fs` based solution(s), and adding nice things like live reloading (and react hot reloading)

@snowkeeper is this something you'd be interesting in looking into?

My ideal final state for the process is to have an npm script that is given a path to the local `keystone` clone, checks out `gh-pages`, builds the site, copies the changes across and commits them, finally switching back to the branch that was previously checked out.

Looks like we could use [the `gh-pages` package](https://www.npmjs.com/package/gh-pages) to implement that without much work.

**Comment by snowkeeper** [comment]
@JedWatson , I can definitely help get this working.  I enjoy putting the docs together, it can be a great learning experience.

I am currently working on adding Session, Middleware, Field and FieldTypes to the reference section.  When done I can hop over to this and have a look.

Excuse my ignorance, but do we have to run gh-pages from the Keystone repo, or would it be easier to setup and run from this repo?

**Comment by morenoh149** [comment]
another option is to use the `gh-pages` branch as the one and only branch for this repo. Then simply keep a generated site in this repo. However, the commit history will get cluttered with generated files for every update.
