### ISSUE TITLE
"node web" start command doesn't exists

### ISSUE THREAD

**Issue by jaydson** [keystonejs/keystonejs-site#50]
On the ["Starting Keystone"](http://keystonejs.com/docs/getting-started/#runningyourapp-startingkeystone) section there's this instruction to run Keystone:  

> Now you're ready to run your application, so execute the following in your project's main folder:
> `node web`

This command doesn't exists, right?

**Comment by jossmac** [comment]
Correct, `node keystone` or `npm start` are mapped

**Comment by jaydson** [comment]
Thanks.
I'll send a PR.

**Comment by jossmac** [comment]
Resolved by #51
