### ISSUE TITLE
Document admin path 

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystonejs-site#52]
added in https://github.com/keystonejs/keystone/pull/1820

**Comment by neagle** [comment]
This is a little embarrassing, as the answer is probably obvious. I just set up keystonejs for the first time and pretty much the first thing I've looked for is how to change the admin path. I see the PR to add the feature, but I can't find any of the updated documentation on how to actually use it. Any chance someone could point me in the right direction?

**Comment by mxstbr** [comment]
`keystone.set('admin path', 'somepath')`, then the admin interface will be at `/somepath`!

**Comment by neagle** [comment]
Is there any kind of rebuilding step that I might be missing? I set that option in my `keystone.init({})` options, but when I restart the app, I still get a 404 at somepath and all the admin under `/keystone`.

**Comment by creynders** [comment]
Did you the version in `master`? I don't think there's a npm release which has it already...

**Comment by neagle** [comment]
That would certainly explain it; I was just using the latest npm release. I'll give that a try later. Thanks!
