### ISSUE TITLE
Documentation recommends "latest"

### ISSUE THREAD

**Issue by josephg** [keystonejs/keystonejs-site#76]
From [http://keystonejs.com/docs/getting-started/](http://keystonejs.com/docs/getting-started/):

package.json
This file describes our project for npm, including the fact that it depends on keystone.

``` json
{
  "dependencies": {
    "keystone": "latest",
    "underscore": "latest"
  },
```

You shouldn't depend on latest - if people do that when keystone breaks compatibility for 4.0 it'll break their app when they npm install again.

Either recommend `"keystone": "^0.3"` or tell people to `npm install --save keystone` if you don't want to have to update the documentation.

**Comment by mxstbr** [comment]
That makes sense, good catch!

**Comment by mxstbr** [comment]
Done, should show up soon!
